
language: php

git:
    depth: 5

php:
    - 7.1
    - 7.2

install:
    - travis_retry composer clear-cache
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - vendor/bin/tale-dev check --report --coverage-php-version=7.1

addons:
    code_climate:
        repo_token: 2a57e80e9a4b33173cc50225fcebd4f2f42434bde036a9bcf2c1dd5d46598321
